import pyray as p

TESTING = True

SCREEN_WIDTH = 800#Private
SCREEN_HEIGHT = 600#Private
SCREEN_VECTOR = p.Vector2(SCREEN_WIDTH, SCREEN_HEIGHT)

HEALTH_BAR_WIDTH = 200

BLC = p.Vector2(10, SCREEN_VECTOR.y - 10)

